# Generated by Django 5.0.3 on 2024-03-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
