# Generated by Django 5.0.3 on 2024-03-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_vehicletype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='headquarters',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
