# Generated by Django 5.0.3 on 2024-03-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_model_vechicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='vechicle_type',
            new_name='vehicle_type',
        ),
    ]
