# Generated by Django 5.0.3 on 2024-03-14 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_vechicle_type_model_vehicle_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('manufacturer', 'name', 'year')},
        ),
    ]
