# Generated by Django 5.0.3 on 2024-03-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_manufacturer_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
