# Generated by Django 5.0.3 on 2024-03-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_model_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='fuel_type',
        ),
    ]
