# Generated by Django 5.0.3 on 2024-06-24 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_manufacturer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cars.variation'),
        ),
    ]
